> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# The interesting Numpy function and Its Uses


### Numpy functions

Write a short introduction about Numpy and list the chosen functions. 
The Numpy is a library in python in which the mathamatical problems can be easly solved by the built-in-functions like multi-dimensional arrays and matrices.It manipulate strings also.High level mathamatics can be easly solved by one line of code using the numpy module or library.  

- numpy.linalg.eig(a)
- numpy.compress(condition, a, axis=None, out=None)
- numpy.insert(arr, obj, values, axis=None)
- numpy.trim_zeros(filt, trim='fb')
- numpy.swapaxes(a, axis1, axis2)

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "18eucs145/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/18eucs145/numpy-array-operations


'https://jovian.ml/18eucs145/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [2]:
# List of functions explained 
function1 = np.linalg.eig
function2 = np.compress
function3 = np.insert
function4 = np.trim_zeros
function5 = np.swapaxes

## Function 1 - np.linalg.eig

Add some explanation about the function in your own words:

This function in numpy linalg.eig is very much usefull to get the eigan values and eigan vectors thoes who know or learning
statistic you would have come across the eigan values and eigan vector to findding it manualy is difficult amd to program it is very complex but when you use this function with just a line of code you could find eigan value and eigan vectors which will be very usefull in solving applications of the eigan value and eigan vector.  

In [3]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4]]

w,v=np.linalg.eig(arr1)
print("Eigan Value= ",format(w))
print("Eigan Vector= ",format(v))

Eigan Value=  [-0.37228132  5.37228132]
Eigan Vector=  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Explanation about example
when you give an square matrix you will get the eigan value and eigan vector as output as array and we can store it in two variables as w,v and can be printed.

In [4]:
# Example 2 - working
w,v = np.linalg.eig(np.array([[12,45,56],[33,77,13],[55,88,34]]))
print("Eigan Value= ",format(w))
print("Eigan Vector= ",format(v))

Eigan Value=  [132.01158269 -28.78888962  19.77730693]
Eigan Vector=  [[-0.51210778 -0.86326867  0.69063451]
 [-0.47613413  0.21306042 -0.51388974]
 [-0.71487195  0.45757235  0.50886276]]


Explanation about example

In this example the entire code is just one line so from this you can use to create an numpy array in the eigan function so it will be so easy to get the answer.

In [5]:
# Example 3 - breaking (to illustrate when it breaks)
arr2=[[34,23,54],[45,44,33]]
w,v=np.linalg.eig(arr2)

LinAlgError: Last 2 dimensions of the array must be square

Explanation about example (why it breaks and how to fix it)

In this example you can see that only the square matrix can be used to find the eigan value and eigan vectors.if you use a non square matrix it will show the above error

Some closing comments about when to use this function.

This function will be very much helpfull in solving the statistical problems that you have with a line of code
Its application are huge in number in datascience field and in many areas.if you use square matrix then you can fix this error

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "18eucs145/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/18eucs145/numpy-array-operations


'https://jovian.ml/18eucs145/numpy-array-operations'

## Function 2 - numpy.compress

Add some explanations


In [20]:
# Example 1 - working
a=np.array([[1, 2], [3, 4], [5, 6]])
np.compress([0, 1,1], a, axis=0)


array([[3, 4],
       [5, 6]])

Explanation about example

This function is used to truncate the given array with given condition as true or flase. In the first parameter is condition second is array variable and third is the axis as coloumn or row

In [22]:
# Example 2 - working
b=[[77,34,55],[66,34,99],[95,35,21]]
a=np.array(b)
np.compress([False,True], a, axis=1)

array([[34],
       [34],
       [35]])

Explanation about example

In this example the condition is given as false and true with regarding the coloumn so it outputs only the second coloumn of the array

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
b=[[77.,43,22],[77.,45],[95,35,21]]
a=np.array(b)
np.compress([False,True,True], a, axis=1)

<ipython-input-24-b15d38e6da4e>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a=np.array(b)


AxisError: axis 1 is out of bounds for array of dimension 1

Explanation about example (why it breaks and how to fix it)

This example breake because of out of index error this because of the second list in the array because there are only two values insted of there so to show the value will be present in that place so it shows error hence to fix it you can give the value were it is missing 

Some closing comments about when to use this function.

This function is used in many places and its easy to use and easy to understand to truncate the array when necessary.

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "18eucs145/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/18eucs145/numpy-array-operations


'https://jovian.ml/18eucs145/numpy-array-operations'

## Function 3 - numpy.insert()

Add some explanations
This function inserts the specific value at the specific place in the list or array or any matrix 

In [33]:
# Example 1 - working
a=[[12,4],[55,6]]
a=np.array(a)
np.insert(a,2,8,axis=1)

array([[12,  4,  8],
       [55,  6,  8]])

Explanation about example

This function inserts the value 8 in coloumn wise and boradcast it and inserts in both the inner list of an array

In [34]:
# Example 2 - working
a=[[12,4],[55,6]]
a=np.array(a)
np.insert(a,2,[4,89],axis=0)

array([[12,  4],
       [55,  6],
       [ 4, 89]])

Explanation about example

This example is used to insert the another row in with just a function

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
a=[[12,4],[55,6]]
a=np.array(a)
np.insert(a,0,[4,89,88],axis=0)

ValueError: could not broadcast input array from shape (1,3) into shape (1,2)

Explanation about example (why it breaks and how to fix it)
In this example you can see that if you try to insert an list that does not match the previous lists so that cannot be broadcasted it can be fixed by giving the correct shape to insert.

Some closing comments about when to use this function.

This function comes in handy when need its one of easiest way to insert the value inside the array.whichis also consumes less time when compared to other methoeds.

In [38]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "18eucs145/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/18eucs145/numpy-array-operations


'https://jovian.ml/18eucs145/numpy-array-operations'

## Function 4 - numpy.trim_zeros()

Add some explanations

This function is used to cut the zeros from array from font and behind the given array

In [5]:
# Example 1 - working
a=np.array([0,0,0,2,3,4,0,6,7,0,0])
np.trim_zeros(a)

array([2, 3, 4, 0, 6, 7])

Explanation about example

This function trims the unwanted zeros at the beginning and at the end

In [7]:
# Example 2 - working
a= np.array([0,0,0,0,1,5,34,0,3,0,0,0])
np.trim_zeros(a,'f')

array([ 1,  5, 34,  0,  3,  0,  0,  0])

Explanation about example

In this example we have trimed the zeroes at the front only the zeros at the end will not be trimed,this can done by given a another parameter as 'f'to trim at the front and 'b' to trim zeros at end

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
a= np.array([[33,67,0],[2,3,0],[0,4,0]])
np.trim_zeros(a,'B')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Explanation about example (why it breaks and how to fix it)

This example brekes because given is an array of matrix to trim the zeros it could not trim inside the sub list that cause the error.To fix it you have specify the which list your going to trim the zeros like a[1] trims the zeros at index 1 zeros

Some closing comments about when to use this function.

This function comes in handy when we need to take the zeros away from the requried array 

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "18eucs145/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/18eucs145/numpy-array-operations


'https://jovian.ml/18eucs145/numpy-array-operations'

## Function 5 - numpy.swapaxes()

Add some explanations

This function is used to swap the axes from row1 to row2 or coloumn1 to coloumn2 or from coloumn to row

In [31]:
# Example 1 - working
a= np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
np.swapaxes(a,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

Explanation about example

This example swaps the coloumn. this fuction swaped the coloumn of a[0,0],a[1,0] to a[1,0],a[1,1]

In [32]:
# Example 2 - working
a= np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
np.swapaxes(a,0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

Explanation about example

This example swaps the row this function swaped the row of a[0,1]to a[1,0]

In [34]:
# Example 3 - breaking (to illustrate when it breaks)

a= np.array([[[0,1,0],[2,3,9]],[[4,5,8],[6,7,8]]])
np.swapaxes(a,0,3)

AxisError: axis2: axis 3 is out of bounds for array of dimension 3

Explanation about example (why it breaks and how to fix it)

In this example you can see the error of axis 3 out of index to fix it you have to change and give the correct dimension


Some closing comments about when to use this function.

This function comes in handy when we need to change or swap between rows or coloumn and you can easly do it by just ease of this function

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'